---

- hosts: 172.26.171.176
  become: true
  tasks:

  - name: Add UE
    command: ip netns add ue1

  - name: Status of UE
    command: ip netns list
    register: ue_list

  - debug:
      var: ue_list.stdout_lines
