---

- hosts: 172.26.164.54
  become: true
  tasks:

  - name: Check MME status
    shell: ps -A | grep open5gs-mmed
    register: grep
    ignore_errors: yes

  - name: MME restart
    include_tasks: mme_restart.yml
    when: not grep.stdout_lines

  - name: MME status display
    include_tasks: mme_status.yml
    register: mme_status
    when: grep.stdout_lines

