---

- hosts: all
  become: true
  tasks:

  - include_tasks: mme_status.yml
    when: ansible_hostname == "open5gs"

  - include_tasks: check_ue_status.yml
    when: ansible_hostname == "srsran"

  - include_tasks: check_iptables.yml
    when: ansible_hostname == "srsran"

  - include_tasks: start_enb.yml
    when: ansible_hostname == "srsran"

  - include_tasks: start_ue.yml
    when: ansible_hostname == "srsran"
