---

- hosts: 172.26.171.176
  become: true
  tasks:

  - name: Attach UE
    command: /home/lab/srsRAN/build/./srsue/src/srsue --rf.device_name=zmq --rf.device_args="tx_port=tcp://*:2001,rx_port=tcp://localhost:2000,id=ue,base_srate=23.04e6" --gw.netns=ue1
